### ISSUE TITLE
colour_table function

### ISSUE THREAD

**Issue by Olivia-Box-Power** [ScotGovAnalysis/sgplot#32]
The colour_table function is documented but not exported.

**Comment by alicebyers5** [comment]
Hi Olivia, This function is only used internally for the vignettes and isn't part of the core functionality of the package, hence why it isn't exported. If you'd really like to use it or view its help file you can access it using `sgplot:::colour_table()`.

**Comment by Olivia-Box-Power** [comment]
Hi Alice. I was just pointing this out as it can cause confusion for users if they see help file documentation for a function in RStudio but then can't run it.

**Comment by Olivia-Box-Power** [comment]
You can use a @noRd roxygen tag https://style.tidyverse.org/documentation.html#internal-functions

**Comment by alicebyers5** [comment]
Ah that's good to know! Thank you 👍
