### ISSUE TITLE
Add details about deploying Shiny app with sgplot

### ISSUE THREAD

**Issue by alice-hannah** [ScotGovAnalysis/sgplot#35]
Extra steps required where Shiny app uses package not on CRAN (e.g. sgplot). It would be good to mention this in the documentation somewhere and provide options to get around this.

**Comment by alicebyers5** [comment]
See discussion (internal): https://engage.cloud.microsoft/main/org/gov.scot/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjcxNjE1Mjc2MTE4ODM1MyJ9?trk_copy_link=V2

**Comment by alice-hannah** [comment]
https://forum.posit.co/t/how-to-use-local-packages-in-shinyapps-io/23709/5

**Comment by alice-hannah** [comment]
The workaround is to replace the full package install folder with install folder from GitHub (to off-network machine). This is unsustainable and unreliable. Long-term solution is to release package to CRAN.
